### ISSUE TITLE
NPE with new response types

### ISSUE THREAD

**Issue by Chris2011** [javierllorente/netbeans-rest-client#13]
when I call google.de or twitter.de with or w/o www doesn't matter, I got this exception:

```
java.lang.NullPointerException
	at org.netbeans.modules.xml.text.breadcrumbs.BreadcrumbProvider.update(BreadcrumbProvider.java:128)
	at org.netbeans.modules.xml.text.breadcrumbs.BreadcrumbProvider.caretUpdate(BreadcrumbProvider.java:89)
	at java.desktop/javax.swing.text.JTextComponent.fireCaretUpdate(JTextComponent.java:412)
	at java.desktop/javax.swing.text.JTextComponent$MutableCaretEvent.fire(JTextComponent.java:4489)
	at java.desktop/javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(JTextComponent.java:4511)
	at org.netbeans.api.editor.caret.EditorCaret$6.run(EditorCaret.java:1733)
	at org.netbeans.modules.editor.lib2.view.ViewUtils.runInEDT(ViewUtils.java:413)
	at org.netbeans.api.editor.caret.EditorCaret.fireStateChanged(EditorCaret.java:1742)
	at org.netbeans.api.editor.caret.EditorCaret.runTransaction(EditorCaret.java:1664)
	at org.netbeans.api.editor.caret.EditorCaret.runTransaction(EditorCaret.java:1559)
	at org.netbeans.api.editor.caret.EditorCaret.modelChanged(EditorCaret.java:1895)
	at org.netbeans.api.editor.caret.EditorCaret.access$1000(EditorCaret.java:143)
	at org.netbeans.api.editor.caret.EditorCaret$ListenerImpl.propertyChange(EditorCaret.java:2604)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8731)
	at java.desktop/javax.swing.text.JTextComponent.setDocument(JTextComponent.java:456)
	at java.desktop/javax.swing.JEditorPane.setEditorKit(JEditorPane.java:1057)
	at com.javierllorente.netbeans.rest.client.ui.ResponsePanel.setContentType(ResponsePanel.java:116)
	at com.javierllorente.netbeans.rest.client.ui.RestClientTopComponent.lambda$updateResponsePanel$5(RestClientTopComponent.java:312)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

I think it has todo with the new MimeTypes. I changed it back to the original one and it worked before. So it seems that this is related to #12

**Comment by javierllorente** [comment]
I can't reproduce this with 0.5.3. I am getting different content ("es" version instead of "de").

**Comment by Chris2011** [comment]
Will check it further. Thx.

**Comment by Chris2011** [comment]
Atm I can't reproduce this exception, but when I try google.de in my daily work IDE, I got this exception:

```
MultiException stack 1 of 2
java.util.ServiceConfigurationError: jakarta.json.spi.JsonProvider: Provider org.glassfish.json.JsonProviderImpl not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1268)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1267)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1270)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at jakarta.json.spi.JsonProvider.provider(JsonProvider.java:124)
	at jakarta.json.Json.createReaderFactory(Json.java:218)
	at org.eclipse.parsson.media.JsonValueBodyReader.<init>(JsonValueBodyReader.java:45)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1356)
	at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:271)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:395)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:466)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2109)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.lambda$getAllServiceHolders$0(AbstractHk2InjectionManager.java:136)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:140)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:30)
	at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:308)
	at org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:152)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:219)
	at org.glassfish.jersey.client.ClientMessageBodyFactory$MessageBodyWorkersConfigurator.postInit(ClientMessageBodyFactory.java:75)
	at org.glassfish.jersey.client.ClientConfig$State.lambda$initRuntime$2(ClientConfig.java:468)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:468)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:834)
	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:181)
	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:199)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38)
	at com.javierllorente.netbeans.rest.client.RestClient.request(RestClient.java:189)
	at com.javierllorente.netbeans.rest.client.ui.RestClientTopComponent.lambda$request$4(RestClientTopComponent.java:284)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
MultiException stack 2 of 2
java.lang.IllegalStateException: Unable to perform operation: create on org.eclipse.parsson.media.JsonValueBodyReader
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:428)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:466)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2109)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.lambda$getAllServiceHolders$0(AbstractHk2InjectionManager.java:136)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:140)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:30)
	at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:308)
	at org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:152)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:219)
	at org.glassfish.jersey.client.ClientMessageBodyFactory$MessageBodyWorkersConfigurator.postInit(ClientMessageBodyFactory.java:75)
	at org.glassfish.jersey.client.ClientConfig$State.lambda$initRuntime$2(ClientConfig.java:468)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:468)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:834)
	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:181)
	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:199)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38)
	at com.javierllorente.netbeans.rest.client.RestClient.request(RestClient.java:189)
	at com.javierllorente.netbeans.rest.client.ui.RestClientTopComponent.lambda$request$4(RestClientTopComponent.java:284)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1420)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2035)
```

I dunno whether smth is missing after installing 0.6.0 or smth weird happened here.

**Comment by Chris2011** [comment]
This is my env

```

Product Version: Apache NetBeans IDE 20
Java: 11.0.19; Java HotSpot(TM) 64-Bit Server VM 11.0.19+9-LTS-224
Runtime: Java(TM) SE Runtime Environment 11.0.19+9-LTS-224
System: Windows 11 version 10.0 running on amd64; Cp1252; de_DE (nb)
User directory: C:\Users\clenz\AppData\Roaming\NetBeans\20
Cache directory: C:\Users\clenz\AppData\Local\NetBeans\Cache\20
```

**Comment by javierllorente** [comment]
This time around you get a different exception. Is that better? :-P
Unfortunately, I can't reproduce it :-(
I have updated jersey to 3.1.5 in the latest release (0.6.0). 
What I have seen is that jersey-media-json-processing and jersey-media-moxy are pulling an old version of parson (1.1.1 instead of 1.1.5).
I have to investigate this further.

**Comment by Chris2011** [comment]
What JDK do you use and which NetBeans version?

**Comment by javierllorente** [comment]
Product Version: Apache NetBeans IDE 20
Java: 21.0.1; OpenJDK 64-Bit Server VM 21.0.1+12-suse-3.1-x8664
Runtime: OpenJDK Runtime Environment 21.0.1+12-suse-3.1-x8664
System: Linux version 6.6.6-1-default running on amd64; UTF-8; es_ES (nb)

**Comment by Chris2011** [comment]
I can try a different JDK.

**Comment by javierllorente** [comment]
Yes, please try a newer version of JDK. So that we have a similar setup.

**Comment by Chris2011** [comment]
I already build it, you know the contributions ;). There i don't get any errors, but I can't remember which JDK it was used.

**Comment by Chris2011** [comment]
Here I'm using JDK 11

**Comment by javierllorente** [comment]
> I already build it, you know the contributions ;). There i don't get any errors, but I can't remember which JDK it was used.

Good :)
So you have built and installed it and it works fine?
It sounds like there is a conflict in the classpath.

**Comment by Chris2011** [comment]
Yes, with a dev IDE building and running, everything is fine. So what does that mean now? Do I need to change here smth with the classpath or what?

**Comment by javierllorente** [comment]
I have tried to reproduce it mixing different versions of jakarta/javax.json. Unfortunately, no exceptions for me.

Do you get the exception if you revert jersey to 3.1.3 (see commit 699816920e35f34d156ed333f9c4f14fd8182851)?
If not, perhaps there is a NB module pulling an old version of a dependency, so that in the end you get a classpath clash problem.

**Comment by Chris2011** [comment]
Ok, luckily or unfortunately my guess was right :D. It is this plugin here, which breaks the rest client: https://github.com/jeddict/jeddict I'm using the latest 6.2.0 version. Also it is not real called jeddict anymore, it is called Jakarta EE application generator and modeler, this is why I thought this could be the problem, when you said smth about jakarta.

**Comment by Chris2011** [comment]
Can we do here smth or is this part of the other plugin?

**Comment by Chris2011** [comment]
So at the end to address this, I should create a ticket at the other repo and link to this issue here.
Or do we have an other option to make a fix dep to your repo that the plugin will your's instead of the other?

**Comment by javierllorente** [comment]
I don't know where the problem is. So, I suggest creating a ticket at the other repo. At least they should know there is a compatibility problem.
